spring:
  datasource:
    url: jdbc:h2:mem:campusdb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  h2:
    console.enabled: true
  sql.init.mode: always
  jackson.default-property-inclusion: NON_NULL
  mvc:
    pathmatch.matching-strategy: ant_path_matcher
server:
  servlet:
    context-path: /api/v1